FROM quay.io/fedora-ostree-desktops/silverblue:42 as release

RUN echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ip-forward.conf && \
    echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/99-ip-forward.conf

COPY ./yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm-ostree override remove firefox firefox-langpacks \
    && rpm-ostree install \
    tailscale \
    zsh \
    code \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && rpm-ostree cleanup -m \
    && ostree container commit

LABEL name="$NAME" \
    summary="Fedora atomic sway container" \
    maintainer="Joe Terlecki" \
    org.opencontainers.image.source="https://github.com/joeterlecki/werkstation"
