ARG NAME="werkstation-sway"
ARG NERDFONTS_VERSION="3.4.0"
ARG GO_VERSION="1.25.4"

FROM busybox AS nerdfonts
RUN wget -q "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/CascadiaCode.zip?agree=true" -O ./cc_font.zip \
    && mkdir -p /fonts-install/usr/local/share/fonts \
    && unzip -o ./cc_font.zip -d /fonts-install/usr/local/share/fonts/ \
    && rm ./cc_font.zip
RUN wget -q "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/NerdFontsSymbolsOnly.zip?agree=true" -O ./nfs_font.zip \
    && mkdir -p /fonts-install/usr/local/share/fonts \
    && unzip -o ./nfs_font.zip -d /fonts-install/usr/local/share/fonts/ \
    && rm ./nfs_font.zip

FROM busybox AS go-binary
ARG GO_VERSION
RUN wget -q "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" -O /tmp/go.tar.gz \
    && mkdir -p /go-install/usr/local \
    && tar -C /go-install/usr/local -xzf /tmp/go.tar.gz \
    && rm /tmp/go.tar.gz

FROM quay.io/fedora-ostree-desktops/sway-atomic:43 as release

COPY --from=nerdfonts /fonts-install/usr /usr/
COPY --from=go-binary /go-install/usr/local/go /usr/local/go

ENV PATH="/usr/local/go/bin:${PATH}" \
    GOPATH="/usr/local/go-packages" \
    GOCACHE="/var/cache/go-build"

RUN echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-ip-forward.conf \
    && echo "net.ipv6.conf.all.forwarding=1" >> /etc/sysctl.d/99-ip-forward.conf

RUN dnf5 config-manager addrepo --from-repofile='https://pkgs.tailscale.com/stable/fedora/tailscale.repo' \
    && dnf5 install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-43.noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-43.noarch.rpm

RUN dnf5 config-manager addrepo --from-repofile='https://download.docker.com/linux/fedora/docker-ce.repo' \
    && dnf5 install -y \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin

RUN dnf5 install -y \
    dnf-plugins-core \
    unzip \
    git \
    wget \
    curl \
    jq \
    neovim \
    emacs \
    kitty \
    ripgrep \
    stow \
    tailscale \
    tmux \
    tree-sitter-cli \
    node \
    zsh \
    && dnf clean all

RUN curl -sSL https://dot.net/v1/dotnet-install.sh -o /tmp/dotnet-install.sh \
    && chmod +x /tmp/dotnet-install.sh \
    && /tmp/dotnet-install.sh --channel 8.0 --install-dir /usr/local/dotnet \
    && /tmp/dotnet-install.sh --channel 9.0 --install-dir /usr/local/dotnet \
    && /tmp/dotnet-install.sh --channel 10.0 --install-dir /usr/local/dotnet \
    && rm /tmp/dotnet-install.sh

ENV DOTNET_ROOT="/usr/local/dotnet" \
    PATH="/usr/local/dotnet:${PATH}" \
    DOTNET_CLI_TELEMETRY_OPTOUT=1

COPY flatpak/flatpak.txt /etc/flatpak-install.txt
COPY flatpak/install-flatpaks.sh /usr/local/bin/install-flatpaks.sh
RUN chmod +x /usr/local/bin/install-flatpaks.sh

COPY flatpak/flatpak-install.service /usr/lib/systemd/user/flatpak-install.service
RUN mkdir -p /usr/lib/systemd/user/default.target.wants \
    && ln -s ../flatpak-install.service /usr/lib/systemd/user/default.target.wants/flatpak-install.service

RUN rpm-ostree override remove firefox firefox-langpacks \
    && rpm-ostree cleanup -m \
    && ostree container commit

LABEL name="${NAME}" \
    summary="Fedora atomic sway with developer tools" \
    maintainer="Joe Terlecki" \
    org.opencontainers.image.source="https://github.com/joeterlecki/werkstation" \
    org.opencontainers.image.description="Sway-based Fedora Atomic container with development tools" \
    org.opencontainers.image.version="43"
