- name: Check if Homebrew is installed
  become: false
  command: brew --version
  register: brew_version
  ignore_errors: yes
- name: Install Homebrew
  become: false
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: brew_version.rc != 0
  args:
    executable: /bin/bash
- name: Install Developer Tools with Homebrew Bundle
  become: false
  command: brew bundle --file {{ playbook_dir }}/dotfiles/homebrew/Brewfile
