- name: Install necessary DNF packages
  become: true
  ansible.builtin.dnf:
    name:
      - git
      - curl
      - wget
      - zip
      - unzip
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - dkms
      - acpid
      - libglvnd-glx
      - libglvnd-opengl
      - libglvnd-devel
      - pkgconfig
      - zsh
      # - power-profiles-daemon Install sepearte step/flag for laptop
    state: latest
- name: "Add rpmfustion repo gpg keys"
  become: true
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
- name: Enable the RPM Free Fusion Free repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-40.noarch.rpm"
    state: present
- name: Enable the RPM Fusion NonFree repository
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-40.noarch.rpm"
    state: present
- name: Install Nvidia Drivers
  become: true
  ansible.builtin.dnf:
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
    state: latest
- name: Uninstall DNF Packages
  become: true
  ansible.builtin.dnf:
    name:
      - dnfdragora
      - xorg-x11-drv-nouveau
    state: absent
