- name: CHecking for previous OH MY ZSH installation
  stat:
    path: "{{ ansible_env.HOME}}/.oh-my-zsh"
  register: ohmyzsh_install
- name: Install OH My ZSH
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    executable: /bin/zsh
  when: not ohmyzsh_install
- name: Set ZSH as default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
- name: Install Powerlevel 10k theme
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest:  "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: master
  when: ohmyzsh_install
- name: Install ZSH Autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    version: master
  when: ohmyzsh_install
- name: Intall ZSH Syntax Highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    version: master 
  when: ohmyzsh_install

