- name: Check if NVM is installed
  become: false
  shell: |
    source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm --version
  args:
    executable: /bin/bash
  register: nvm_check
  ignore_errors: true
- name: Install nvm
  become: false
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash

  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: nvm_check.rc != 0
- name: Install Latest Node NVM
  become: false
  shell: source {{ ansible_env.HOME  }}/.bashrc && nvm install --lts
  args:
    executable: /bin/bash
- name: Install AstroNvim Vanilla # TODO clone personal later
  become: false
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/template
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    force: true
    # separate_git_dir: "{{ ansible_env.HOME }}/.config/nvim"
