---
- name: Enable COPR repository for lazygit
  command: dnf copr enable atim/lazygit -y
  args:
    creates: /etc/yum.repos.d/_copr\:copr.fedorainfracloud.org\:atim\:lazygit.repo
- name: Enable COPR repository for bottom
  command: dnf copr enable atim/bottom -y
  args:
    creates: /etc/yum.repos.d/_copr\:copr.fedorainfracloud.org\:atim\:bottom.repo
- name: Check if NVM is installed
  shell: |
    source ~/.nvm/nvm.sh && nvm --version
  register: nvm_check
  ignore_errors: true
- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: nvm_check.rc != 0
- name: Download gdu binary
  get_url:
    url: https://github.com/dundee/gdu/releases/download/v5.29.0/gdu_linux_amd64.tgz
    dest: /tmp/gdu_linux_amd64.tgz
- name: Extract gdu binary
  unarchive:
    src: /tmp/gdu_linux_amd64.tgz
    dest: /tmp/gdu_linux
    remote_src: yes
    mode: "0755"
- name: Ensure gdu name
  command: mv /tmp/gdu_linux/gdu_linux_amd64 /usr/local/bin/gdu
# - name: Ensure gdu is executable
#   file:
#     path: /usr/local/bin/gdu
#     mode: "0755"
- name: Instal Neovim Dependencies
  ansible.builtin.dnf:
    name:
      - tree-sitter-cli
      - ripgrep
      - neovim
      - lazygit
      - bottom
- name: Download lazydocker binary
  get_url:
    url: https://github.com/jesseduffield/lazydocker/releases/download/v0.23.3/lazydocker_0.23.3_Linux_x86_64.tar.gz
    dest: /tmp/lazydocker.tar.gz
- name: Extract lazydocker binary
  unarchive:
    src: /tmp/lazydocker.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
# - name: Ensure lazydocker is executable
#   file:
#     path: /usr/local/bin/lazydocker
#     mode: "0755"
